name = "mcp-oauth-worker"
main = "src/index.ts"
compatibility_date = "2025-08-16"

[observability]
enabled = true

[env.production.vars]
GITHUB_CLIENT_ID = ""
GITHUB_CLIENT_SECRET = ""
JWT_PRIVATE_KEY = ""
JWT_PUBLIC_KEY = ""
REFRESH_ENCRYPTION_KEY = ""
ACCESS_TOKEN_ENCRYPTION_KEY = ""
WORKER_BASE_URL = ""

[[env.production.kv_namespaces]]
binding = "AUTH_KV"
id = ""

[env.development.vars]
GITHUB_CLIENT_ID = ""
GITHUB_CLIENT_SECRET = ""
JWT_PRIVATE_KEY = ""
JWT_PUBLIC_KEY = ""
REFRESH_ENCRYPTION_KEY = ""
ACCESS_TOKEN_ENCRYPTION_KEY = ""
WORKER_BASE_URL = "http://localhost:8787"

[[env.development.kv_namespaces]]
binding = "AUTH_KV"
preview_id = ""
